TEST_HOTEL_RESULTS_RESPONSE = {
    'search_id': 'some_id',
    'search': {
        'adults': 1,
        'children': [],
        'rooms': [{'guests': [{'age': 30, 'is_child': False, 'citizenship': 'ru'}]}],
        'check_in': '26.06.2022',
        'check_out': '01.07.2022',
        'city': 6308866,
        'hotel_id': None,
        'location': {
            'iata': 6308866,
            'country': 'Россия',
            'type': 'City',
            'type_description': 'Город',
            'typeRu': 'Город',
            'name': 'Белогорск, Россия',
        },
    },
    'hotels': [
        {
            'id': '1',
            'name': 'Тестотель (Островок)',
            'phone': None,
            'email': None,
            'photos': [
                {
                    'url': 'some_url',
                    'thumb': 'some_thumb',
                },
            ],
            'description': 'Плата за доступ в номерах',
            'policy': None,
            'facilities': [{'name': 'Питание и напитки', 'list': ['Ресторан', 'Бар']}],
            'city': 'Белогорск',
            'country': 'Россия',
            'location': {'latitude': 50.921287, 'longitude': 128.473881},
            'stars': 2,
            'category_name': 'Hotel',
            'rating': [],
            'address': 'Белогорск, Ордос 1',
            'trip_advisor_rating': None,
            'check_in_time': '14:00',
            'check_out_time': '12:00',
            'max_check_in_time': None,
            'max_check_out_time': None,
            'important_information': None,
            'min_fare': 487,
            'min_fares': {'RUB': 487},
            'min_price': 487,
            'min_prices': {'RUB': 487},
            'price_details': {'RUB': {'aac_fee': 0}},
            'liked': False,
            'has_free_cancellation': True,
            'travel_policy': {'is_violated': False, 'notices': [], 'reason_codes': []},
            'search_id': 'some_hotel_id',
            'contract': None,
            'is_contract_only': False,
            'is_provider_contract': True,
        },
        {
            'id': '2',
            'name': 'Тестотель 2 (Полуостров)',
            'phone': None,
            'email': None,
            'photos': [],
            'description': 'Плата за доступ в номерах',
            'policy': None,
            'facilities':[
                {
                    'name': 'Общие',
                    'list': [
                        'Wi-Fi доступен на всей территории',
                        'Платный Wi-Fi',
                        'Парковка',
                        'Бесплатная парковка',
                        'Парковка на территории',
                        'Смешанная парковка',
                        'Допускается размещение домашних животных',
                    ],
                },
                {'name': 'Сервисы', 'list': ['Wi-Fi']},
                {
                    'name': 'Стойка регистрации',
                    'list': ['Сейф', 'Камера хранения багажа', 'Круглосуточная стойка регистрации']
                },
                {'name': 'Разное', 'list': ['Кондиционер']},
                {
                    'name': 'Услуги бизнес-центра',
                    'list': [
                        'Конференц-зал/Банкетный зал',
                        'Факс/Ксерокопирование',
                        'Комната переговоров',
                    ],
                },
                {
                    'name': 'Питание и напитки',
                    'list': ['Бар', 'Ресторан (меню)', 'Электрический чайник'],
                },
            ],
            'city': 'Белогорск',
            'country': 'Россия',
            'location': {'latitude': 50.921287, 'longitude': 128.473881},
            'stars': 2,
            'category_name': 'Hotel',
            'rating': [],
            'address': 'Белогорск, Ордос 2',
            'trip_advisor_rating': None,
            'check_in_time': '14:00',
            'check_out_time': '12:00',
            'max_check_in_time': None,
            'max_check_out_time': None,
            'important_information': None,
            'min_fare': 487,
            'min_fares': {'RUB': 487},
            'min_price': 487,
            'min_prices': {'RUB': 487},
            'price_details': {'RUB': {'aac_fee': 0}},
            'liked': False,
            'has_free_cancellation': True,
            'travel_policy': {'is_violated': False, 'notices': [], 'reason_codes': []},
            'search_id': 'some_hotel_id',
            'contract': None,
            'is_contract_only': False,
            'is_provider_contract': False,
        },
        {
            'id': '3',
            'name': 'Тестотель 3',
            'phone': None,
            'email': None,
            'photos': [
                {
                    'url': 'some_url',
                    'thumb': 'some_thumb',
                },
            ],
            'description': 'Плата за доступ в номерах',
            'policy': None,
            'facilities': [{'name': 'Питание и напитки', 'list': ['Ресторан', 'Бар']}],
            'city': 'Белогорск',
            'country': 'Россия',
            'location': {'latitude': 50.921287, 'longitude': 128.473881},
            'stars': 3,
            'category_name': 'Hotel',
            'rating': [],
            'address': 'Белогорск, Ордос 3',
            'trip_advisor_rating': None,
            'check_in_time': '14:00',
            'check_out_time': '12:00',
            'max_check_in_time': None,
            'max_check_out_time': None,
            'important_information': None,
            'min_fare': 587,
            'min_fares': {'RUB': 587},
            'min_price': 587,
            'min_prices': {'RUB': 587},
            'price_details': {'RUB': {'aac_fee': 0}},
            'liked': False,
            'has_free_cancellation': True,
            'travel_policy': {'is_violated': False, 'notices': [], 'reason_codes': []},
            'search_id': 'some_hotel_id',
            'contract': None,
            'is_contract_only': False,
            'is_provider_contract': False,
        },
        {
            'id': '4',
            'name': 'Тестотель 4',
            'phone': None,
            'email': None,
            'photos': [],
            'description': 'Плата за доступ в номерах',
            'policy': None,
            'facilities': [{'name': 'Питание и напитки', 'list': ['Ресторан', 'Бар']}],
            'city': 'Белогорск',
            'country': 'Россия',
            'location': {'latitude': 50.921287, 'longitude': 128.473881},
            'stars': 3,
            'category_name': 'Hotel',
            'rating': [],
            'address': 'Белогорск, Ордос 4',
            'trip_advisor_rating': None,
            'check_in_time': '14:00',
            'check_out_time': '12:00',
            'max_check_in_time': None,
            'max_check_out_time': None,
            'important_information': None,
            'min_fare': 587,
            'min_fares': {'RUB': 587},
            'min_price': 587,
            'min_prices': {'RUB': 587},
            'price_details': {'RUB': {'aac_fee': 0}},
            'liked': False,
            'has_free_cancellation': True,
            'travel_policy': {'is_violated': False, 'notices': [], 'reason_codes': []},
            'search_id': 'some_hotel_id',
            'contract': None,
            'is_contract_only': False,
            'is_provider_contract': True,
        },
    ],
    'total': 4,
    'offset': 0,
    'limit': 20,
    'is_completed': True,
}
